# Generated by Django 3.1.3 on 2022-04-29 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeecode', models.CharField(max_length=50)),
                ('empdept', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=12, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('joiningdate', models.DateField(null=True)),
                ('resume', models.FileField(default=None, max_length=250, null=True, upload_to='empresume/')),
                ('photo', models.FileField(default=None, max_length=250, null=True, upload_to='empimg/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
