# Generated by Django 3.1.3 on 2022-05-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeeducation_employeeexperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeentry',
            name='resume',
        ),
        migrations.AddField(
            model_name='employeeentry',
            name='rm',
            field=models.FileField(null=True, upload_to='media/empresume'),
        ),
        migrations.AlterField(
            model_name='employeeentry',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/empimg'),
        ),
    ]
