# Generated by Django 3.1.3 on 2022-05-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20220504_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeentry',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='employeeentry',
            name='age',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeeentry',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
