# Generated by Django 3.1.3 on 2022-05-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20220504_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeentry',
            name='photo',
            field=models.FileField(max_length=250, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employeeentry',
            name='rm',
            field=models.FileField(max_length=250, null=True, upload_to=''),
        ),
    ]
