# Generated by Django 3.1.3 on 2022-05-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20220510_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeentry',
            name='rm',
        ),
        migrations.AlterField(
            model_name='employeeentry',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
